package my.domain;

import java.io.Serializable;
import java.util.Date;
import my.util.BasePo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table food
 */
public class Food extends BasePo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.id
     *
     * @mbg.generated
     */
    private Long id;
    
    private Long empId;
    
    private String empName;

	/**
     * Database Column Remarks:
     *   食材名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   采购来源
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   库存
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.stock
     *
     * @mbg.generated
     */
    private Integer stock;

    /**
     * Database Column Remarks:
     *   过期时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.expire_time
     *
     * @mbg.generated
     */
    private Date expireTime;

    /**
     * Database Column Remarks:
     *   报告图片地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.report_pic
     *
     * @mbg.generated
     */
    private String reportPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table food
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.id
     *
     * @return the value of food.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.id
     *
     * @param id the value for food.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    public Long getEmpId() {
		return empId;
	}

	public void setEmpId(Long empId) {
		this.empId = empId;
	}

	public String getEmpName() {
		return empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.name
     *
     * @return the value of food.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.name
     *
     * @param name the value for food.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.address
     *
     * @return the value of food.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.address
     *
     * @param address the value for food.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.stock
     *
     * @return the value of food.stock
     *
     * @mbg.generated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.stock
     *
     * @param stock the value for food.stock
     *
     * @mbg.generated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.expire_time
     *
     * @return the value of food.expire_time
     *
     * @mbg.generated
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.expire_time
     *
     * @param expireTime the value for food.expire_time
     *
     * @mbg.generated
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.report_pic
     *
     * @return the value of food.report_pic
     *
     * @mbg.generated
     */
    public String getReportPic() {
        return reportPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.report_pic
     *
     * @param reportPic the value for food.report_pic
     *
     * @mbg.generated
     */
    public void setReportPic(String reportPic) {
        this.reportPic = reportPic == null ? null : reportPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", address=").append(address);
        sb.append(", stock=").append(stock);
        sb.append(", expireTime=").append(expireTime);
        sb.append(", reportPic=").append(reportPic);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}