package my.domain;

import java.io.Serializable;
import my.util.BasePo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tablewear
 */
public class Tablewear extends BasePo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tablewear.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tablewear.check_pic
     *
     * @mbg.generated
     */
    private String checkPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tablewear
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tablewear.id
     *
     * @return the value of tablewear.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tablewear.id
     *
     * @param id the value for tablewear.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tablewear.check_pic
     *
     * @return the value of tablewear.check_pic
     *
     * @mbg.generated
     */
    public String getCheckPic() {
        return checkPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tablewear.check_pic
     *
     * @param checkPic the value for tablewear.check_pic
     *
     * @mbg.generated
     */
    public void setCheckPic(String checkPic) {
        this.checkPic = checkPic == null ? null : checkPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablewear
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", checkPic=").append(checkPic);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}