package my.vo;

import java.io.Serializable;
import java.math.BigDecimal;
import my.util.BasePo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table dish
 */
public class DishVo extends BasePo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.id
     *
     * @mbg.generated
     */
    private Long id;
    
    private Long dishTypeId;
    
    private String dishTypeName;

	public String getDishTypeName() {
		return dishTypeName;
	}

	public void setDishTypeName(String dishTypeName) {
		this.dishTypeName = dishTypeName;
	}

	/**
     * Database Column Remarks:
     *   菜品名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.name
     *
     * @mbg.generated
     */
    private String name;
    
    /**
     *   详情
     */
    private String detail;

    public String getDetail() {
		return detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	/**
     * Database Column Remarks:
     *   单价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     * Database Column Remarks:
     *   参照图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish.img
     *
     * @mbg.generated
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dish
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.id
     *
     * @return the value of dish.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.id
     *
     * @param id the value for dish.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }
    

    public Long getDishTypeId() {
		return dishTypeId;
	}

	public void setDishTypeId(Long dishTypeId) {
		this.dishTypeId = dishTypeId;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.name
     *
     * @return the value of dish.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.name
     *
     * @param name the value for dish.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.price
     *
     * @return the value of dish.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.price
     *
     * @param price the value for dish.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish.img
     *
     * @return the value of dish.img
     *
     * @mbg.generated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish.img
     *
     * @param img the value for dish.img
     *
     * @mbg.generated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", price=").append(price);
        sb.append(", img=").append(img);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}