package my.vo;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

import my.util.BasePo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table employee
 */
public class EmployeeVo extends BasePo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   员工账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     * Database Column Remarks:
     *   员工密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.pwd
     *
     * @mbg.generated
     */
    private String pwd;

    /**
     * Database Column Remarks:
     *   员工姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.name
     *
     * @mbg.generated
     */
    private String name;
    
    private String tel;

    public String getTel() {
		return tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
     * Database Column Remarks:
     *   健康证图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.health_pic
     *
     * @mbg.generated
     */
    private String healthPic;

    /**
     * Database Column Remarks:
     *   健康证过期时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.health_expire
     *
     * @mbg.generated
     */

    @JsonFormat(pattern = "yyyy-MM-dd",timezone = "GMT+8")
    private Date healthExpire;

    /**
     * Database Column Remarks:
     *   员工账号状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employee
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.account
     *
     * @return the value of employee.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.account
     *
     * @param account the value for employee.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.pwd
     *
     * @return the value of employee.pwd
     *
     * @mbg.generated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.pwd
     *
     * @param pwd the value for employee.pwd
     *
     * @mbg.generated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.name
     *
     * @return the value of employee.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.name
     *
     * @param name the value for employee.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.health_pic
     *
     * @return the value of employee.health_pic
     *
     * @mbg.generated
     */
    public String getHealthPic() {
        return healthPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.health_pic
     *
     * @param healthPic the value for employee.health_pic
     *
     * @mbg.generated
     */
    public void setHealthPic(String healthPic) {
        this.healthPic = healthPic == null ? null : healthPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.health_expire
     *
     * @return the value of employee.health_expire
     *
     * @mbg.generated
     */
    public Date getHealthExpire() {
        return healthExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.health_expire
     *
     * @param healthExpire the value for employee.health_expire
     *
     * @mbg.generated
     */
    public void setHealthExpire(Date healthExpire) {
        this.healthExpire = healthExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.status
     *
     * @return the value of employee.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.status
     *
     * @param status the value for employee.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", account=").append(account);
        sb.append(", pwd=").append(pwd);
        sb.append(", name=").append(name);
        sb.append(", healthPic=").append(healthPic);
        sb.append(", healthExpire=").append(healthExpire);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}