package my.vo;

import java.io.Serializable;
import java.util.Date;
import my.util.BasePo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table spot_check
 */
public class SpotCheckVo extends BasePo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot_check.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   抽查人id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot_check.emp_id
     *
     * @mbg.generated
     */
    private Long empId;
    
    private String empName;
    
    private String dishName;

	/**
     * Database Column Remarks:
     *   抽查时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot_check.check_time
     *
     * @mbg.generated
     */
    private Date checkTime;

    /**
     * Database Column Remarks:
     *   抽查菜品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot_check.dish_id
     *
     * @mbg.generated
     */
    private Long dishId;

    /**
     * Database Column Remarks:
     *   抽查结果(0、不合格，1、合格)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot_check.result
     *
     * @mbg.generated
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spot_check
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot_check.id
     *
     * @return the value of spot_check.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot_check.id
     *
     * @param id the value for spot_check.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot_check.emp_id
     *
     * @return the value of spot_check.emp_id
     *
     * @mbg.generated
     */
    public Long getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot_check.emp_id
     *
     * @param empId the value for spot_check.emp_id
     *
     * @mbg.generated
     */
    public void setEmpId(Long empId) {
        this.empId = empId;
    }

    public String getEmpName() {
		return empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	public String getDishName() {
		return dishName;
	}

	public void setDishName(String dishName) {
		this.dishName = dishName;
	}

    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot_check.check_time
     *
     * @return the value of spot_check.check_time
     *
     * @mbg.generated
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot_check.check_time
     *
     * @param checkTime the value for spot_check.check_time
     *
     * @mbg.generated
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot_check.dish_id
     *
     * @return the value of spot_check.dish_id
     *
     * @mbg.generated
     */
    public Long getDishId() {
        return dishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot_check.dish_id
     *
     * @param dishId the value for spot_check.dish_id
     *
     * @mbg.generated
     */
    public void setDishId(Long dishId) {
        this.dishId = dishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot_check.result
     *
     * @return the value of spot_check.result
     *
     * @mbg.generated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot_check.result
     *
     * @param result the value for spot_check.result
     *
     * @mbg.generated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_check
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", empId=").append(empId);
        sb.append(", checkTime=").append(checkTime);
        sb.append(", dishId=").append(dishId);
        sb.append(", result=").append(result);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}