package my.mapper;

import java.util.List;

import my.domain.DishType;
import my.vo.DishTypeVo;

public interface DishTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_type
     *
     * @mbg.generated
     */
    int insert(DishType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_type
     *
     * @mbg.generated
     */
    int insertSelective(DishType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_type
     *
     * @mbg.generated
     */
    DishType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DishType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DishType record);
    
    List<DishTypeVo> queryDishType(DishTypeVo vo);
}