package my.mapper;

import java.util.List;

import my.domain.Dish;
import my.vo.DishVo;

public interface DishMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish
     *
     * @mbg.generated
     */
    int insert(Dish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish
     *
     * @mbg.generated
     */
    int insertSelective(Dish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish
     *
     * @mbg.generated
     */
    Dish selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Dish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dish record);
    
    List<DishVo> queryDish(DishVo vo);
}