package my.mapper;

import java.util.List;

import my.domain.LeaveMessage;
import my.vo.LeaveMessageVo;

public interface LeaveMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbg.generated
     */
    int insert(LeaveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbg.generated
     */
    int insertSelective(LeaveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbg.generated
     */
    LeaveMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LeaveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LeaveMessage record);
    
    List<LeaveMessageVo> queryLeaveMessage(LeaveMessageVo vo);
}