package my.mapper;

import java.util.List;

import my.domain.SpotCheck;
import my.vo.SpotCheckVo;

public interface SpotCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_check
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_check
     *
     * @mbg.generated
     */
    int insert(SpotCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_check
     *
     * @mbg.generated
     */
    int insertSelective(SpotCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_check
     *
     * @mbg.generated
     */
    SpotCheck selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_check
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SpotCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spot_check
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SpotCheck record);
    
    List<SpotCheckVo> querySpotCheck(SpotCheckVo vo);
}