package my.mapper;

import java.util.List;

import my.domain.Tablewear;
import my.vo.TablewearVo;

public interface TablewearMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablewear
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablewear
     *
     * @mbg.generated
     */
    int insert(Tablewear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablewear
     *
     * @mbg.generated
     */
    int insertSelective(Tablewear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablewear
     *
     * @mbg.generated
     */
    Tablewear selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablewear
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Tablewear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tablewear
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Tablewear record);
    
    List<TablewearVo> queryTablewear(TablewearVo vo);
}